server:
  context-path: /user
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    data-username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: /
      prefix: .jsp
  http:
      encoding:
        charset: UTF-8
        force: true
mybatis:
  type-aliases-package: com.baizhi.user.entity
  mapper-locations: com/baizhi/user/dao/UserDao.xml